In [1]:
import pandas as pd

heights_A = pd.Series([176.2, 158.4, 167.6, 156.2, 161.4], index=['s1','s2','s3','s4','s5'])
print(heights_A.shape)

weights_A = pd.Series([85.1, 90.2, 76.8, 80.4,78.9], index=['s1','s2','s3','s4','s5']) # create series
print(weights_A.dtypes)

df_A = pd.DataFrame({'Student_height':heights_A, # create dataframe
        'Student_weight':weights_A})
print(df_A.shape)

from scipy import stats
import numpy as np
np.random.seed(100)

heights_B = pd.Series(np.random.normal(170, 25, 5), index=['s1','s2','s3','s4','s5'])
weights_B = pd.Series(np.random.normal(75, 2, 5), index=['s1','s2','s3','s4','s5'])

print(np.mean(heights_B))

df_B = pd.DataFrame({'Student_height':heights_B,
        'Student_weight':weights_B})
print(df_B.columns)

p = pd.Panel.from_dict({'ClassA':df_A, 'ClassB':df_B})
print(p.shape)

(5,)
float64
(5, 2)
172.37417741633146
Index(['Student_height', 'Student_weight'], dtype='object')

AttributeError: ignored

In [2]:
# import pandas and numpy 
import pandas as pd
import numpy as np
 
# creating simple array
data = np.array(['g','e','e','k','s','f', 'o','r','g','e','e','k','s'])
ser = pd.Series(data,index=[10,11,12,13,14,15,16,17,18,19,20,21,22])
  
  
# accessing a element using index element
print(ser)

10    g
11    e
12    e
13    k
14    s
15    f
16    o
17    r
18    g
19    e
20    e
21    k
22    s
dtype: object

In [3]:
# Python code demonstrate creating 
# DataFrame from dict narray / lists 
# By default addresses.
 
import pandas as pd
 
# intialise data of lists.
data = {'Name':['Tom', 'nick', 'krish', 'jack'],
        'Age':[20, 21, 19, 18]}
 
# Create DataFrame
df = pd.DataFrame(data)
#del df['Name']
 
# Print the output.
print(df.Name)
print(df[:2])

0      Tom
1     nick
2    krish
3     jack
Name: Name, dtype: object
   Name  Age
0   Tom   20
1  nick   21

In [4]:
import pandas as pd

data = [{'a': 1, 'b': 2}, {'a': 5, 'b': 10, 'c': 20}]
df = pd.DataFrame(data, columns=['a', 'b'])
print(df.shape)

(2, 2)

In [5]:
import pandas as pd

data = [{'a': 1, 'b': 2}, {'a': 5, 'b': 10, 'c': 20}]
df = pd.DataFrame(data)
print(df.shape)

(2, 3)

In [6]:
import pandas as pd

s = pd.Series([89.2, 76.4, 98.2, 75.9], index=list('abcd'))
print(s[['c', 'a']])

c    98.2
a    89.2
dtype: float64

In [7]:
s = pd.Series([99, 32, 67],list('abc'))
s.isin([67, 32])

a    False
b     True
c     True
dtype: bool

In [8]:
import pandas as pd
import numpy as np
z = np.arange(10, 16)
s = pd.Series(z, index=list('abcdef'))
#Accessing 3rd element of s.
s[2] # ---> Returns '12' 
#Accessing 4th element of s.
s['d'] # ---> Returns '13'
### ALSO SAME AS ABOVE ###
s.get(2) # ---> Returns '12'
s.get('d') # ---> Returns '13'

### SLICING ###
s[1:4] # unlike as indexing by number
s['b':'e']  # when index values are used last element is included in the slice

b    11
c    12
d    13
e    14
dtype: int64

In [9]:
heights_A = pd.Series([176.2, 158.4, 167.6, 156.2, 161.4], index=['s1','s2','s3','s4','s5'])
print(heights_A[1])
print(heights_A.iloc[1:4])
weights_A = pd.Series([85.1, 90.2, 76.8, 80.4,78.9], index=['s1','s2','s3','s4','s5'])
df_A = pd.DataFrame({'Student_height':heights_A,
        'Student_weight':weights_A})  
height = df_A['Student_height']
print(type(height))

df_s1s2 = df_A.loc['s1':'s2']  #new df with just two columns
print(df_s1s2)

df_s2s5s1 = df_A.loc[['s2','s5','s1']] # new df in specific order of columns
print(df_s2s5s1)

cols = []
for x in df_A.index:
  if x.endswith('1') or x.endswith('4'):
      cols.append(x)
      
df_s1s4 = df_A.loc[cols]
print(df_s1s4)

158.4
s2    158.4
s3    167.6
s4    156.2
dtype: float64
<class 'pandas.core.series.Series'>
    Student_height  Student_weight
s1           176.2            85.1
s2           158.4            90.2
    Student_height  Student_weight
s2           158.4            90.2
s5           161.4            78.9
s1           176.2            85.1
    Student_height  Student_weight
s1           176.2            85.1
s4           156.2            80.4

In [10]:
heights_A = pd.Series([176.2, 158.4, 167.6, 156.2, 161.4], index=['s1','s2','s3','s4','s5'])
#print(heights_A[1])
#print(heights_A.iloc[1:4])
weights_A = pd.Series([85.1, 90.2, 76.8, 80.4,78.9], index=['s1','s2','s3','s4','s5'])
df_A = pd.DataFrame({'Student_height':heights_A,
        'Student_weight':weights_A})  
height = df_A['Student_height']
df_A.to_csv('classA.csv', sep=',')

df_A2 = pd.read_csv('classA.csv')
print(df_A2)

df_A3 = pd.read_csv('classA.csv', index_col=0)
print(df_A3)

from scipy import stats
import numpy as np
np.random.seed(100)
heights_B = pd.Series(np.random.normal(170, 25, 5), index=['s1','s2','s3','s4','s5'])
np.random.seed(100)
weights_B = pd.Series(np.random.normal(75, 12, 5), index=['s1','s2','s3','s4','s5'])

#print(np.mean(heights_B))

df_B = pd.DataFrame({'Student_height':heights_B,
        'Student_weight':weights_B})
df_B.to_csv('classB.csv', index=None)
df_B2 = pd.read_csv('classB.csv')
print(df_B2)

df_B3 = pd.read_csv('classB.csv',header=None)
print(df_B3)

df_B4 = pd.read_csv('classB.csv',header=None, skiprows=2, )
print(df_B4)

  Unnamed: 0  Student_height  Student_weight
0         s1           176.2            85.1
1         s2           158.4            90.2
2         s3           167.6            76.8
3         s4           156.2            80.4
4         s5           161.4            78.9
    Student_height  Student_weight
s1           176.2            85.1
s2           158.4            90.2
s3           167.6            76.8
s4           156.2            80.4
s5           161.4            78.9
   Student_height  Student_weight
0      126.255863       54.002814
1      178.567010       79.112165
2      198.825895       88.836430
3      163.689099       71.970768
4      194.533020       86.775849
                    0                  1
0      Student_height     Student_weight
1  126.25586317363256  54.00281432334363
2  178.56701008318754  79.11216483993003
3   198.8258950640911  88.83642963076373
4  163.68909908696526  71.97076756174332
5  194.53301967378079  86.77584944341478
            0          1
0  178.567010  79.112165
1  198.825895  88.836430
2  163.689099  71.970768
3  194.533020  86.775849

In [11]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.rand(5,2))
df.index = [ 'row_' + str(i) for i in range(1, 6) ]  # used to set custom index column
df

              0         1
row_1  0.136707  0.575093
row_2  0.891322  0.209202
row_3  0.185328  0.108377
row_4  0.219697  0.978624
row_5  0.811683  0.171941

In [12]:
import pandas as pd

dates = pd.date_range(start ='09-01-2017', end ='09-15-2017')
print(dates[2])
datelist = ['14-Sep-2017', '9-Sep-2017']
dates_to_be_searched = pd.to_datetime(datelist)
print(dates_to_be_searched)

print(dates_to_be_searched.isin(dates))

arraylist = [['classA']*5 + ['classB']*5, ['s1', 's2', 's3','s4', 's5']*2]
mi_index = pd.MultiIndex.from_arrays(arraylist)  # from_touples, etc etc
print(mi_index.levels)

2017-09-03 00:00:00
DatetimeIndex(['2017-09-14', '2017-09-09'], dtype='datetime64[ns]', freq=None)
[ True  True]
[['classA', 'classB'], ['s1', 's2', 's3', 's4', 's5']]

In [13]:
d = pd.date_range('11-Sep-2017', '17-Sep-2017', freq='2D')
print(d)
print(d + pd.Timedelta('1 days 2 hours')) #moves every date ahead by 1 day 2hrs
print(len(pd.date_range('11-Sep-2017', '17-Sep-2017', freq='2D')))


d = pd.date_range('11-Sep-2017', '17-Sep-2017', freq='2D')
len(d[d.isin(pd.to_datetime(['12-09-2017', '15-09-2017']))])

DatetimeIndex(['2017-09-11', '2017-09-13', '2017-09-15', '2017-09-17'], dtype='datetime64[ns]', freq='2D')
DatetimeIndex(['2017-09-12 02:00:00', '2017-09-14 02:00:00',
               '2017-09-16 02:00:00', '2017-09-18 02:00:00'],
              dtype='datetime64[ns]', freq='2D')
4

1

In [14]:
import numpy as np
heights_A = pd.Series([176.2, 158.4, 167.6, 156.2, 161.4], index=['s1','s2','s3','s4','s5'])
#print(heights_A[1])
#print(heights_A.iloc[1:4])
weights_A = pd.Series([85.1, 90.2, 76.8, 80.4,78.9], index=['s1','s2','s3','s4','s5'])
df_A = pd.DataFrame({'Student_height':heights_A,'Student_weight':weights_A})  

#print(df_A)
df_A['Student_weight']['s3'] = 'NaN'   # assign value to specific cell
df_A['Student_height']['s3'] = 'NaN'   # df[col_name][row_name/row_number]

#df_A.loc[['s3']] = [['new_value','new_value2']]   ## same as above, just no col_name needed
#df_A.loc[['s5']] = [[np.nan,np.nan]]   ## same as above, just no col_name needed
df_A['Student_weight']['s5'] = 'NaN'
#print(df_A)
df_A2 = df_A.dropna(how='any')
print(df_A2)

    Student_height  Student_weight
s1           176.2            85.1
s2           158.4            90.2
s4           156.2            80.4

In [25]:
df = pd.DataFrame({'temp':pd.Series(28 + 10*np.random.randn(10)),
                   'rain':pd.Series(100 + 50*np.random.randn(10)),
                   'location':list('AAAAABBBBB')})

print(df.head)

replacements = {'location': {'A':'Hyderabad', 'B':'Mumbai'}}
df = df.replace(replacements, regex=True) # replace col_names
print(df.head)

##to filter rows, based on a column strings with a specific pattern and modify them
mumbai_data = df.loc[df.location.str.contains('umb'),:]
print(mumbai_data.head(2))

##groupby method can be used to group data and perform various function on each group.
regions = df.groupby('location')
print(regions.mean())

<bound method NDFrame.head of         temp        rain location
0  37.370822   77.202654        A
1  35.310003  159.481113        A
2  41.615561   15.469159        A
3  24.737619   32.180048        A
4  28.556760   38.378274        A
5  30.223996   72.778042        B
6  13.567830   66.591413        B
7  20.436477  100.365728        B
8  36.164540   69.353063        B
9  35.504448  164.987404        B>
<bound method NDFrame.head of         temp        rain   location
0  37.370822   77.202654  Hyderabad
1  35.310003  159.481113  Hyderabad
2  41.615561   15.469159  Hyderabad
3  24.737619   32.180048  Hyderabad
4  28.556760   38.378274  Hyderabad
5  30.223996   72.778042     Mumbai
6  13.567830   66.591413     Mumbai
7  20.436477  100.365728     Mumbai
8  36.164540   69.353063     Mumbai
9  35.504448  164.987404     Mumbai>
        temp       rain location
5  30.223996  72.778042   Mumbai
6  13.567830  66.591413   Mumbai
                temp      rain
location
Hyderabad  33.518153  64.54225
Mumbai     27.179458  94.81513

In [16]:
import numpy as np
heights_A = pd.Series([176.2, 158.4, 167.6, 156.2, 161.4], index=['s1','s2','s3','s4','s5'])
#print(heights_A[1])
#print(heights_A.iloc[1:4])
weights_A = pd.Series([85.1, 90.2, 76.8, 80.4,78.9], index=['s1','s2','s3','s4','s5'])
df_A = pd.DataFrame({'Student_height':heights_A,'Student_weight':weights_A})


## Remember that you're writing the condition in terms of what you want to keep, not in terms of what you want to drop
#df1 = df[(df.a != -1) & (df.b != -1)]  # and condtion for both True
#df2 = df[(df.a != -1) | (df.b != -1)]  # OR condition for both True

df_A_filter1 = df_A[(df_A.Student_height > 160) & (df_A.Student_weight < 80)]
#df_A_filter1 = df_A[(df_A['Student_height'] > 160) | (df_A['Student_weight'] < 80)]
#print(df_A_filter1)

df_A_filter2 = df_A[df_A.index.str.endswith('5')]  ##  USE THIS FILTER, for index filtering
print(df_A_filter2)

df_A['Gender'] = ['M', 'F', 'M', 'M', 'F']

df_groups = df_A.groupby('Gender')
print(df_groups.mean())

    Student_height  Student_weight
s5           161.4            78.9
        Student_height  Student_weight
Gender
F           159.900000       84.550000
M           166.666667       80.766667

In [17]:

df = pd.DataFrame(np.random.rand(10,4),columns=['A', 'B', 'C', 'D'],index=[ 'r1', 'r2', 'r3', 'row4', 'row5', 'row6', 'r7', 'r8', 'r9', 'row10'])
print(df)
g = df.groupby(df.index.str.len())
#print(df)
#print(g.max())
g.filter(lambda x: len(x) > 1)  # removes row where given condition is true, and returns column
#print(df[lambda x: x.index.str.endswith('3')]) # returns row r3
#print(df)

#df = pd.DataFrame(np.random.rand(3,4),columns=['A', 'B', 'C', 'D'],index=[ 'r1', 'r2', 'r3',])
#print(df)
#print(df.iloc[df.B > 0.45])
#pd.read_csv()

              A         B         C         D
r1     0.769115  0.250695  0.285896  0.852395
r2     0.975006  0.884853  0.359508  0.598859
r3     0.354796  0.340190  0.178081  0.237694
row4   0.044862  0.505431  0.376252  0.592805
row5   0.629942  0.142600  0.933841  0.946380
row6   0.602297  0.387766  0.363188  0.204345
r7     0.276765  0.246536  0.173608  0.966610
r8     0.957013  0.597974  0.731301  0.340385
r9     0.092056  0.463498  0.508699  0.088460
row10  0.528035  0.992158  0.395036  0.335596

             A         B         C         D
r1    0.769115  0.250695  0.285896  0.852395
r2    0.975006  0.884853  0.359508  0.598859
r3    0.354796  0.340190  0.178081  0.237694
row4  0.044862  0.505431  0.376252  0.592805
row5  0.629942  0.142600  0.933841  0.946380
row6  0.602297  0.387766  0.363188  0.204345
r7    0.276765  0.246536  0.173608  0.966610
r8    0.957013  0.597974  0.731301  0.340385
r9    0.092056  0.463498  0.508699  0.088460

In [18]:
heights_A = pd.Series([176.2, 158.4, 167.6, 156.2, 161.4], index=['s1','s2','s3','s4','s5'])
#print(heights_A[1])
#print(heights_A.iloc[1:4])
weights_A = pd.Series([85.1, 90.2, 76.8, 80.4,78.9], index=['s1','s2','s3','s4','s5'])
df_A = pd.DataFrame({'Student_height':heights_A,'Student_weight':weights_A})
df_A['Gender'] = ['M', 'F', 'M', 'M', 'F']


## creating new row to add in that dataframe
s = pd.Series( [165.4, 82.7, 'F'], index=['Student_height', 'Student_weight', 'Gender'], name='s6')

##  adding that row to old df
df_AA = df_A.append(s)
#print(df_AA)
#print(s)



import numpy as np
np.random.seed(100)
heights_B = pd.Series(np.random.normal(170, 25, 5), index=['s1','s2','s3','s4','s5'])
np.random.seed(100)
weights_B = pd.Series(np.random.normal(75, 12, 5), index=['s1','s2','s3','s4','s5'])

#print(np.mean(heights_B))

df_B = pd.DataFrame({'Student_height':heights_B,
        'Student_weight':weights_B})

new_index =  [ 's7', 's8', 's9', 's10', 's11']
df_B.index = new_index
df_B['Gender'] =  ['F', 'M', 'F', 'F', 'M']
#print(df_B)

df = pd.concat([df_AA,df_B])
print(df)

     Student_height  Student_weight Gender
s1       176.200000       85.100000      M
s2       158.400000       90.200000      F
s3       167.600000       76.800000      M
s4       156.200000       80.400000      M
s5       161.400000       78.900000      F
s6       165.400000       82.700000      F
s7       126.255863       54.002814      F
s8       178.567010       79.112165      M
s9       198.825895       88.836430      F
s10      163.689099       71.970768      F
s11      194.533020       86.775849      M

In [19]:

nameid = pd.Series(range(101, 111))
name = pd.Series(['person' + str(i) for i in range(1, 11)])

master  = pd.DataFrame({'nameid':nameid, 'name':name})
transaction = pd.DataFrame({'nameid':[108, 108, 108,103], 'product':['iPhone', 'Nokia', 'Micromax', 'Vivo']})


mdf = pd.merge(master,transaction)
print(mdf)

   nameid     name   product
0     103  person3      Vivo
1     108  person8    iPhone
2     108  person8     Nokia
3     108  person8  Micromax

In [22]:
import pandas as pd

data = [{'a': 1, 'b': 2}, {'a': 5, 'b': 10, 'c': 20}]
df = pd.DataFrame(data, columns=['a', 'b'])
print(df.shape)

(2, 2)

In [23]:
s = pd.Series([89.2, 76.4, 98.2, 75.9], index=list('abcd'))
print('b' in s)
print(len(pd.period_range('11-Sep-2017', '17-Sep-2017', freq='M')))
import pandas as pd

s1 = pd.Series([0, 1, 2, 3])
s2 = pd.Series([0, 1, 2, 3])
s3 = pd.Series([0, 1, 4, 5])
d = pd.concat([s1, s2, s3], axis=1)
print(d.shape)
print(len(pd.bdate_range('11-Sep-2017', '17-Sep-2017', freq='2D')))
import pandas as pd

s = pd.Series([9.2, 'hello', 89])
print(s.dtype)

True
1
(4, 3)
4
object